server:
  servlet:
    context-path: /demo

quartz:
  enabled: true

job: 
  frequency: 4000
  repeatCount: 19

logging:
  level:
    root : INFO
    org.springframework.web: WARN
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure.security: INFO
    it.fabioformosa: DEBUG
    it.fabiof: DEBUG

quartz-manager:
  jobClass: it.fabiof.demo.SampleJob
  security:
    login-model:
      form-login-enabled: true
      userpwd-filter-enabled : false
    jwt:
      enabled: true
      secret: "bibidibobidiboo"
      expiration-in-sec: 28800  # 8 hours
      header-strategy:
        enabled: false
        header: "Authorization"
      cookie-strategy:
        enabled: true
        cookie: AUTH-TOKEN
  accounts:
    in-memory:
      enabled: true
      users:
        - name: admin
          password: admin
          roles:
            - ADMIN      
